### PR TITLE
Update default theme to match Hacker0x01 (hackerone)

### PR DESCRIPTION
**Pull request by marr**
I'm submitting this WIP PR for the following three reasons:
1) I prefer the coding style of this repo over react-datepicker. This comes down to a requirement which involves decoupling the value shown in a text input control based off the value of the date picker that I have in a UI component for tilt.com.
2) I prefer the styling of react-datepicker over this repo. This is the WIP part, as I'm trying to maintain the flex styling used here originally. To see progress, this is what it currently looks like:
screen shot 2015-08-02 at 3 26 09 pm

I wanted to emulate the style here eventually:
screen shot 2015-08-02 at 3 35 51 pm

3) This repo may receive more usage if it had a better default style.

Also just looking for discussion around this. I didn't think the header rendered as a table made semantic sense, so I changed/simplified that a bit. Also I had to move the week-day-names into a different place so I could get the header look unified.

### CODE REVIEW

**Comment by radubrehar** [comment]
Thanks for the PR. We're definitely interested in improving our styling.
We'll have a look at this and merge it in!

**Comment by marr** [comment]
Sure thing. I see you just merged in some new stuff related to styles. I will have to rebase this one. Do you have any screenshots of the design you are trying to go for?

**Comment by radubrehar** [comment]
Changes I've made are related to layout only, I've switched table layout to flex layout. So if you could rebase your branch would be great. We need to think this through and give people the ability to choose a bare-bones design (maybe the current one) and an enhanced design (a theme), which you are proposing.

**Comment by marr** [comment]
Thanks for the recent changes around the layout! I redid this PR and mostly just touched `theme.styl` and `constants.styl` save for one flex option I changed in `structure.styl`. 
screen shot 2015-08-06 at 11 56 00 pm

**Comment by marr** [comment]
I'm open to ideas on how to provide the barebones version you mention and the themed one, if you feel it is necessary.

**Comment by radubrehar** [comment]
Thanks, coming up with feedback in the weekend

**Comment by radubrehar** [comment]
The theme looks really nice

**Comment by radubrehar** [comment]
In the screenshot, is 7th the minDate?

**Comment by marr** [comment]
Yes, which is also the current date. ie, `minDate={moment()}`

**Comment by marr** [comment]
In the case of the mindate a few days in the past:

screen shot 2015-08-07 at 1 36 39 am

**Comment by marr** [comment]
I'm curious if you have layout ideas for getting the boxes to be more square with flexbox. I'm not too strong with flexbox yet and I wasn't sure how to do that.

**Comment by radubrehar** [comment]
It's all based on the picker width/height. So give the picker a bit more height and they adjust. Or less width. 
Or you can play with `.date-picker .dp-table .dp-cell { padding: 10px 5px }` (defaults to 5px)

**Comment by radubrehar** [comment]
Flexbox gives us a lot more `flex`ibility than the table layout we had before :)

**Comment by radubrehar** [comment]
Hey, I've just released `3.1.0` with support for theming, see https://github.com/zippyui/react-date-picker#theming

Thanks for contributing.
Will improve theming infrastructure even more in the near future.

**Comment by radubrehar** [comment]
If you want to improve the readme with screenshots of the two themes (with default picker configs - so both header and footer), please go ahead.

**Comment by marr** [comment]
Thanks Radu! Excited to see this land.

**Pull request merged**
