### PR TITLE
Added support for weekdays

### PR DESCRIPTION
**Pull request by christianalfoni**
Thanks for building, in my opinion, the only correctly implemented React Date Picker :-)

It was a joy working on your code and the "renderDay" and "onDayRender" methods takes advantage of React in a really good way.

The only thing we are missing to get going with this lib is weekdays. Hopefully I have implemented this in a way you accept and we can use the official repo for this.

Thanks again for building this, great job!

### CODE REVIEW

**Comment by radubrehar** [comment]
Wow :) thanks for the very positive feedback! Glad you find this useful.

Yeah, this is how we develop components, going the React way, not against it.
Hopefully you'll find other React components we've developed useful as well.

Will look into your PR and come back with feedback.

**Comment by christianalfoni** [comment]
Hi again, great thanks! :-)

I have been working a bit with it now and realised that it is not really a good idea to trigger both "onWeekChange" and "onChange" when a week is selected.

It would be preferable to only trigger the respective callback passed into the component, but still as you click a week to change the internal date to the first date of that week... I think :-)

**Comment by christianalfoni** [comment]
Okay, so I updated that in the code. Now it only trigger "onChange" on normal day change and "onWeekChange" on actual week change. Then it is up to the developer what to do when a week changes. In the example code it uses the first day of the week to set the date of the date picker.

**Comment by radubrehar** [comment]
Hi @christianalfoni thanks for contributing. I've merged the PR, with a couple of changes. I don't think it's a good idea to trigger a selection on week number click. In fact, I made week numbers very dumb, they are just presentational.

If you want to attach behavior, use the `renderWeekNumber` prop, and hook your own logic there.
What's your opinion on this?

PS: also added `weekNumberName` to default to  '' but customizable, to show in the header.

**Comment by radubrehar** [comment]
PS: if you want to help us with more feedback, feel free to do so here #57

**Comment by christianalfoni** [comment]
I agree :-) Push as much logic as possible on the specific app implementation. Everybody wants something different.

**Comment by radubrehar** [comment]
Totally agree!

**Comment by radubrehar** [comment]
@christianalfoni we're building our website right now. Can we quote you?

> Thanks for building, in my opinion, the only correctly implemented react-date-picker :-) it  was a joy working on your code!

**Comment by christianalfoni** [comment]
For sure :-)

**Pull request merged**
