### PR TITLE
Avoiding an error when no date is selected

### PR DESCRIPTION
**Pull request by jetpacmonkey**
As of #17 being fixed (version 2.0.10) react-date-picker was throwing an error when given `null` as its `value`/`defaultValue`.

### CODE REVIEW

**Comment by jetpacmonkey** [comment]
I'm not sure if I was supposed to update the version number and the build, or if that's something you would typically do yourself.

**Comment by crittelmeyer** [comment]
:+1:

**Comment by zippyui-react** [comment]
Thanks for the fix. We have just merged the pull request and also fixed another bug: when the `date` prop was set to a value, and then reset to `null`, the value from `this.state.defaultDate` was rendered as selected. Just changed that to always render `this.props.date` in the picker as selected, if specified.

So if you now have `<DatePicker date={null} />` then the date picker is rendered with no selected date.

Please update to `2.0.11`, which is already on npm.
Appreciate your contributions! You can help us make `react-date-picker` the best date picker around!

**Comment by zippyui-react** [comment]
We've just added tests and CI with CircleCI.com at https://circleci.com/gh/zippyui/react-date-picker so we can make sure regressions are highly unlikely

**Pull request merged**
